In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

## Drivers Data

In [49]:
Drivers_df = pd.read_csv("..\\Data\\drivers.csv")

In [50]:
Drivers_df.head()

,driver_id,rating,vehicle_type,signup_date,last_active,city,acceptance_rate
0,D00000,3.1,SUV,2025-01-20,2025-01-06 18:23:09.312275,Cairo,0.679555
1,D00001,5.0,Sedan,2023-03-27,2025-04-27 01:44:02.472554,Nairobi,0.548786
2,D00002,4.5,Motorcycle,2024-05-02,2025-03-07 19:24:46.367672,Nairobi,0.593724
3,D00003,5.0,Motorcycle,2023-04-16,2025-03-26 19:16:24.253793,Nairobi,0.990000
4,D00004,4.4,Motorcycle,2023-05-28,2025-04-08 18:54:44.649615,Lagos,0.519773

## Riders Data

In [51]:
Riders_df = pd.read_csv("..\\Data\\riders.csv")

In [52]:
Riders_df.head()

,user_id,signup_date,loyalty_status,age,city,avg_rating_given,churn_prob,referred_by
0,R00000,2025-01-24,Bronze,34.729629,Nairobi,5.0,0.142431,R00001
1,R00001,2024-09-09,Bronze,34.571020,Nairobi,4.7,0.674161,NaN
2,R00002,2024-09-07,Bronze,47.133960,Lagos,4.2,0.510379,NaN
3,R00003,2025-03-17,Bronze,41.658628,Nairobi,4.9,0.244779,NaN
4,R00004,2024-08-20,Silver,40.681709,Lagos,3.9,0.269960,R00002

## Trips Data

In [53]:
Trips_df = pd.read_csv("..\\Data\\trips.csv")
Trips_df.head(5)

,trip_id,user_id,driver_id,fare,surge_multiplier,tip,payment_type,pickup_time,dropoff_time,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng,weather,city,loyalty_status
0,T000000,R05207,D00315,12.11,1.0,0.00,Card,2024-11-27 18:41:50+02:27,2024-11-27 19:33:50+02:27,-1.108123,36.912209,-1.068155,36.875377,Foggy,Nairobi,Bronze
1,T000001,R09453,D03717,8.73,1.0,0.02,Card,2024-10-28 23:13:48+00:14,2024-10-28 23:26:48+00:14,6.675266,3.515740,6.641734,3.525620,Sunny,Lagos,Gold
2,T000002,R00567,D02035,19.68,1.0,0.00,Card,2025-02-17 05:36:41+02:27,2025-02-17 05:52:41+02:27,-1.248589,37.010668,-1.273182,37.018586,Cloudy,Nairobi,Bronze
3,T000003,R09573,D02657,16.43,1.0,0.01,Mobile Money,2024-06-18 19:27:14+02:05,2024-06-18 19:32:14+02:05,29.819554,31.188780,29.837689,31.232978,Cloudy,Cairo,Bronze
4,T000004,R03446,D01026,8.70,1.0,1.06,Card,2024-10-05 09:58:16+02:27,2024-10-05 10:28:16+02:27,-1.676479,36.729219,-1.638395,36.694063,Sunny,Nairobi,Gold

In [54]:
Trips_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   trip_id           200000 non-null  str
 1   user_id           200000 non-null  str
 2   driver_id         200000 non-null  str
 3   fare              200000 non-null  float64
 4   surge_multiplier  200000 non-null  float64
 5   tip               200000 non-null  float64
 6   payment_type      200000 non-null  str
 7   pickup_time       200000 non-null  str
 8   dropoff_time      200000 non-null  str
 9   pickup_lat        200000 non-null  float64
 10  pickup_lng        200000 non-null  float64
 11  dropoff_lat       200000 non-null  float64
 12  dropoff_lng       200000 non-null  float64
 13  weather           200000 non-null  str
 14  city              200000 non-null  str
 15  loyalty_status    200000 non-null  str
dtypes: float64(7), str(9)
memory usage: 42.1 MB

## Sessions Data

In [55]:
Sessions_df = pd.read_csv("..\\Data\\sessions.csv")
Sessions_df.head(5)

,session_id,rider_id,session_time,time_on_app,pages_visited,converted,city,loyalty_status
0,S000000,R08605,2025-04-27 18:57:06+02:05,79,4,1,Cairo,Bronze
1,S000001,R08823,2025-04-27 07:32:22+02:27,101,3,0,Nairobi,Silver
2,S000002,R05342,2025-04-27 23:17:25+02:05,12,1,0,Cairo,Bronze
3,S000003,R05057,2025-04-27 14:40:25+00:14,19,1,0,Lagos,Silver
4,S000004,R09614,2025-04-27 08:31:22+00:14,4,1,0,Lagos,Bronze

## Promotions Data

In [56]:
promotions_df = pd.read_csv("..\\Data\\promotions.csv")
promotions_df.head(5)

,promo_id,promo_name,promo_type,promo_value,start_date,end_date,target_segment,city_scope,ab_test_groups,test_allocation,success_metric
0,P000,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-25,All,Nairobi,['All'],[1.0],Usage Frequency
1,P001,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-22,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
2,P002,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-16,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
3,P003,Loyalty Bonus,points,100.0,2025-04-26,2025-05-04,Gold+,Nairobi,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
4,P004,Loyalty Bonus,points,100.0,2025-04-26,2025-05-15,Gold+,Nairobi,['All'],[1.0],Usage Frequency

### correlation/Linear Relationship between independent and dependent

In [ ]:
trips = Trips_df
riders = Riders_df
sessions = Sessions_df
drivers = Drivers_df
promotions = promotions_df

sessions.rename(columns = {'rider_id':'user_id'}, inplace = True)
merged  = trips.merge(riders, on='user_id', how='left').merge(sessions, on='user_id',                                                     
how='left').merge(drivers, on='driver_id', how='left', suffixes=('_rider', '_driver'))

In [65]:
numeric_cols = merged.select_dtypes(include=['float64']).columns.tolist()
churn_corr = merged[numeric_cols].corr()['churn_prob'].drop('churn_prob').sort_values()

churn_corr

pages_visited      -0.003730
converted          -0.003654
avg_rating_given   -0.003537
acceptance_rate    -0.002387
rating             -0.002005
time_on_app        -0.001502
tip                -0.001150
pickup_lat         -0.000634
dropoff_lat        -0.000626
age                -0.000554
surge_multiplier    0.000160
fare                0.000277
dropoff_lng         0.009446
pickup_lng          0.009449
Name: churn_prob, dtype: float64

### Feature Selection using Mutual Info Classification

In [66]:
merged['churn'] = (merged['churn_prob'] > 0.5).astype(int)

In [67]:
merged.columns

Index(['trip_id', 'user_id', 'driver_id', 'fare', 'surge_multiplier', 'tip',
       'payment_type', 'pickup_time', 'dropoff_time', 'pickup_lat',
       'pickup_lng', 'dropoff_lat', 'dropoff_lng', 'weather', 'city_x',
       'loyalty_status_x', 'signup_date_rider', 'loyalty_status_y', 'age',
       'city_y', 'avg_rating_given', 'churn_prob', 'referred_by', 'session_id',
       'session_time', 'time_on_app', 'pages_visited', 'converted',
       'city_rider', 'loyalty_status', 'rating', 'vehicle_type',
       'signup_date_driver', 'last_active', 'city_driver', 'acceptance_rate',
       'churn'],
      dtype='str')

In [70]:
cat_cols = data.select_dtypes(include='object').columns

for col in cat_cols:
    print(f"{col}: {data[col].nunique()}")

C:\Users\admin\AppData\Local\Temp\ipykernel_11744\3406661125.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = data.select_dtypes(include='object').columns

payment_type: 3
weather: 4
city_x: 3
loyalty_status_x: 4
loyalty_status_y: 4
city_y: 3
referred_by: 1660
session_id: 50000
city_rider: 3
loyalty_status: 4
vehicle_type: 4
signup_date_driver: 1090
last_active: 5000
city_driver: 3

In [72]:
from sklearn.feature_selection import mutual_info_classif

#get our features
# encode categorical
# have our x and y
# fit into mutual info
# get the mi_scores
# assisgn scores to the column names

drop_cols = ['trip_id', 'user_id', 'driver_id', 'churn_prob', 'pickup_time', 'dropoff_time','signup_date_rider','session_time','session_id','referred_by','signup_date_driver','last_active']
feature_cols =[c for c in merged.columns if c not in drop_cols]

data = merged[feature_cols]
data = pd.get_dummies(data, columns=data.select_dtypes(include='object').columns.tolist(), dtype=int)

x = data.drop(columns = 'churn')
y = data['churn']

# filling missing values
num_cols = x.select_dtypes(include=['int64', 'float64']).columns
x[num_cols] = x[num_cols].fillna(x[num_cols].median())
x = x.fillna(0)

# Confirm no missing values remain
print(x.isna().sum().sum())



mi_scores = mutual_info_classif(x,y, random_state = 42)
print(mi_scores)

C:\Users\admin\AppData\Local\Temp\ipykernel_11744\2724826463.py:14: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data = pd.get_dummies(data, columns=data.select_dtypes(include='object').columns.tolist(), dtype=int)

0
[0.01015145 0.05657187 0.00248983 0.2903317  0.29063311 0.29028427
 0.2899507  0.3186512  0.01790285 0.01084517 0.036995   0.01320938
 0.01281908 0.01372629 0.11658763 0.00537076 0.07934556 0.01198834
 0.0028356  0.02147889 0.13801033 0.05979666 0.056514   0.05744521
 0.13814861 0.00540653 0.00239141 0.03217485 0.13795172 0.00579487
 0.00257021 0.03176143 0.05992291 0.05584761 0.05728531 0.05975667
 0.05607559 0.05699201 0.13845016 0.00581479 0.00174077 0.03143634
 0.00114607 0.0096053  0.0621834  0.11251304 0.06028907 0.05616585
 0.05764292]